### ISSUE TITLE
Go through failed tests and correct mistakes

### ISSUE THREAD

**Issue by summercms** [summercms/Parser-PHP-v3.x.x#134]
Merge all the work done.

**Comment by ayumi-cloud** [comment]
Work to be done - will try and get this done this month.

1. List all api changes in jan 2021 updates
2. Create fresh merge
3. Add all new pr's one by one

**Comment by summercms** [comment]
https:// github. com/ WhichBrowser/ Parser-PHP/ pull/ 647

**Comment by summercms** [comment]
Add Fake bots detection <<<

**Comment by summercms** [comment]
Fake Ahrefs Bot to new pr

**Comment by summercms** [comment]
Baidu <<<<

**Comment by summercms** [comment]
Add Gmail Image Proxy to email apps  <<<<<<<<<<

**Comment by summercms** [comment]
Added extra regex for the Facebook chat-app and added facebook app version number <<<<<

**Comment by summercms** [comment]
Alienforce Browser <<<<<<<<

**Comment by summercms** [comment]
Add Tesla Browser as coming up blank in tests at the moment 
Re-look at some of the user agents

**Comment by summercms** [comment]
AOL Desktop (extra regex) and AOL Shield (added)

**Comment by summercms** [comment]
https://github.com/WhichBrowser/Parser-PHP/pull/316
https://github.com/WhichBrowser/Parser-PHP/pull/278
https://github.com/WhichBrowser/Parser-PHP/pull/258
https://github.com/WhichBrowser/Parser-PHP/pull/256
https://github.com/WhichBrowser/Parser-PHP/pull/106
